<center>
<img src="https://laelgelcpublic.s3.sa-east-1.amazonaws.com/lael_50_years_narrow_white.png.no_years.400px_96dpi.png" width="300" alt="LAEL 50 years logo">
<h3>APPLIED LINGUISTICS GRADUATE PROGRAMME (LAEL)</h3>
</center>
<hr>

# Corpus Linguistics - Study 1 - Phase 2 - Anna

## Inventory filename characters in source corpus

In [1]:
from pathlib import Path

source_dir = Path("corpus/00_source")

filename_characters = set()

for path in source_dir.iterdir():
    if path.is_file():
        filename_characters.update(path.name)

filename_characters

{' ',
 ',',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'L',
 'M',
 'N',
 'O',
 'P',
 'R',
 'S',
 'T',
 '_',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'l',
 'm',
 'n',
 'o',
 'p',
 'r',
 's',
 't',
 'u',
 'v',
 'x',
 'z',
 'ã',
 'ç',
 'ê'}

## Normalise source corpus filenames

- lower the case
- replace ' ' and ',' with '_'
- replace '.' with '_' except when it precedes the file extension
- replace 'ã' with 'a'
- replace 'ç' with 'c'
- replace 'ê' with 'e'

In [2]:
from pathlib import Path

source_dir = Path("corpus/00_source")

rename_log = []

for path in source_dir.iterdir():
    if not path.is_file():
        continue

    stem = path.stem
    suffix = path.suffix.lower()

    new_stem = (
        stem.lower()
        .replace(" ", "_")
        .replace(",", "_")
        .replace(".", "_")
        .replace("ã", "a")
        .replace("ç", "c")
        .replace("ê", "e")
    )

    new_path = path.with_name(f"{new_stem}{suffix}")

    if path.name != new_path.name:
        if new_path.exists():
            raise FileExistsError(f"Cannot rename {path.name}: {new_path.name} already exists")

        path.rename(new_path)
        rename_log.append((path.name, new_path.name))

rename_log

[('PI_INF e EF_5.txt', 'pi_inf_e_ef_5.txt'),
 ('RO_INF_20.txt', 'ro_inf_20.txt'),
 ('ES_EM_15.txt', 'es_em_15.txt'),
 ('AM_EF_3.txt', 'am_ef_3.txt'),
 ('DF_EM_50.txt', 'df_em_50.txt'),
 ('PB_EF_6.txt', 'pb_ef_6.txt'),
 ('RO_EF_107.txt', 'ro_ef_107.txt'),
 ('RO_EM_33.txt', 'ro_em_33.txt'),
 ('MT_EF_48.txt', 'mt_ef_48.txt'),
 ('MT_EF_30.txt', 'mt_ef_30.txt'),
 ('AM_INF_23.txt', 'am_inf_23.txt'),
 ('GO_EF_4.txt', 'go_ef_4.txt'),
 ('SC_INF e EF_30.txt', 'sc_inf_e_ef_30.txt'),
 ('RO_EF_28.txt', 'ro_ef_28.txt'),
 ('RS_EF_9.txt', 'rs_ef_9.txt'),
 ('AM_INF_35.txt', 'am_inf_35.txt'),
 ('MG_EM_127.txt', 'mg_em_127.txt'),
 ('PA_EM_105.txt', 'pa_em_105.txt'),
 ('GO_EM_20.txt', 'go_em_20.txt'),
 ('BA_EM_60.txt', 'ba_em_60.txt'),
 ('GO_INF_15.txt', 'go_inf_15.txt'),
 ('RN_INF_17.txt', 'rn_inf_17.txt'),
 ('MT_EF_90.txt', 'mt_ef_90.txt'),
 ('AC_EM_53.txt', 'ac_em_53.txt'),
 ('PR_EM_115.txt', 'pr_em_115.txt'),
 ('AM_INF_30.txt', 'am_inf_30.txt'),
 ('PR_EM_20.txt', 'pr_em_20.txt'),
 ('MA_EM_50.txt', 'ma_em_50.txt'),
 ('AL_EF_9.txt', 'al_ef_9.txt'),
 ('TO_INF_10.txt', 'to_inf_10.txt'),
 ('AM_INF_11.txt', 'am_inf_11.txt'),
 ('CE_INF_16.txt', 'ce_inf_16.txt'),
 ('AM_EM_8.txt', 'am_em_8.txt'),
 ('PB_EM_109.txt', 'pb_em_109.txt'),
 ('PB_EF_56.txt', 'pb_ef_56.txt'),
 ('RS_EM_1.txt', 'rs_em_1.txt'),
 ('AL_EF_43.txt', 'al_ef_43.txt'),
 ('MG_EF_CH_GEO_1.txt', 'mg_ef_ch_geo_1.txt'),
 ('PR_INF_EF_6.txt', 'pr_inf_ef_6.txt'),
 ('BA_EF_9.txt', 'ba_ef_9.txt'),
 ('AM_EF_57.txt', 'am_ef_57.txt'),
 ('PB_EM_92.txt', 'pb_em_92.txt'),
 ('MG_EM_55.txt', 'mg_em_55.txt'),
 ('MG_INF_objetivos.txt', 'mg_inf_objetivos.txt'),
 ('AM_EM_32.txt', 'am_em_32.txt'),
 ('RN_INF_36.txt', 'rn_inf_36.txt'),
 ('PE_EF_38.txt', 'pe_ef_38.txt'),
 ('MT_EF_77.txt', 'mt_ef_77.txt'),
 ('PI_EM_15.txt', 'pi_em_15.txt'),
 ('MG_EF_Linguagens_LP_15.txt', 'mg_ef_linguagens_lp_15.txt'),
 ('BA_EM_33.txt', 'ba_em_33.txt'),
 ('RO_INF_38.txt', 'ro_inf_38.txt'),
 ('ES_INF_Intro_17.txt', 'es_inf_intro_17.txt'),
 ('ES_INF_16.txt', 'es_inf_16.txt'),
 ('TO_EM_66.txt', 'to_em_66.txt'),
 ('RO_EM_3.txt', 'ro_em_3.txt'),
 ('RN_EF_37.txt', 'rn_ef_37.txt'),
 ('AC_INF e EF_12.txt', 'ac_inf_e_ef_12.txt'),
 ('RS_EM_44.txt', 'rs_em_44.txt'),
 ('PA_INF_15.txt', 'pa_inf_15.txt'),
 ('AP_INF e EF_3.txt', 'ap_inf_e_ef_3.txt'),
 ('AL_EF_84.txt', 'al_ef_84.txt'),
 ('RJ_INF_INTRO_6.txt', 'rj_inf_intro_6.txt'),
 ('RN_EF_25.txt', 'rn_ef_25.txt'),
 ('RO_EM_53.txt', 'ro_em_53.txt'),
 ('GO_INF e EF_4.txt', 'go_inf_e_ef_4.txt'),
 ('PB_EM_4.txt', 'pb_em_4.txt'),
 ('DF_EF_2.txt', 'df_ef_2.txt'),
 ('BA_EF_16.txt', 'ba_ef_16.txt'),
 ('PI_EM_35.txt', 'pi_em_35.txt'),
 ('SC_EM_12.txt', 'sc_em_12.txt'),
 ('PB_INF_6.txt', 'pb_inf_6.txt'),
 ('CE_EM_1.txt', 'ce_em_1.txt'),
 ('AM_INF_21.txt', 'am_inf_21.txt'),
 ('RN_EM_4.txt', 'rn_em_4.txt'),
 ('AP_EF_21.txt', 'ap_ef_21.txt'),
 ('AM_EF_1.txt', 'am_ef_1.txt'),
 ('SC_EM_31.txt', 'sc_em_31.txt'),
 ('PE_EF_49.txt', 'pe_ef_49.txt'),
 ('MT_EF_81.txt', 'mt_ef_81.txt'),
 ('RR_EM_60.txt', 'rr_em_60.txt'),
 ('ES_INF_11.txt', 'es_inf_11.txt'),
 ('MT_EF_17.txt', 'mt_ef_17.txt'),
 ('PA_EM_87.txt', 'pa_em_87.txt'),
 ('MG_EM_115.txt', 'mg_em_115.txt'),
 ('AM_EF_5.txt', 'am_ef_5.txt'),
 ('AP_EF_33.txt', 'ap_ef_33.txt'),
 ('RO_EF_10.txt', 'ro_ef_10.txt'),
 ('PE_EF_43.txt', 'pe_ef_43.txt'),
 ('CE_EM_35.txt', 'ce_em_35.txt'),
 ('PE_EF_24.txt', 'pe_ef_24.txt'),
 ('MG_EM_117.txt', 'mg_em_117.txt'),
 ('PR_EF_12.txt', 'pr_ef_12.txt'),
 ('RO_EM_89.txt', 'ro_em_89.txt'),
 ('PI_INF e EF_9.txt', 'pi_inf_e_ef_9.txt'),
 ('RN_EF_22.txt', 'rn_ef_22.txt'),
 ('RO_EF_7.txt', 'ro_ef_7.txt'),
 ('RR_EM_38.txt', 'rr_em_38.txt'),
 ('AM_EF_55.txt', 'am_ef_55.txt'),
 ('AP_EF_42.txt', 'ap_ef_42.txt'),
 ('RS_EM_34.txt', 'rs_em_34.txt'),
 ('BA_EM_62.txt', 'ba_em_62.txt'),
 ('MG_EM_58.txt', 'mg_em_58.txt'),
 ('PI_EM_53.txt', 'pi_em_53.txt'),
 ('MG_EM_28.txt', 'mg_em_28.txt'),
 ('RN_EM_47.txt', 'rn_em_47.txt'),
 ('MG_EF_Linguagens_Arte_1.txt', 'mg_ef_linguagens_arte_1.txt'),
 ('CE_INF_8.txt', 'ce_inf_8.txt'),
 ('RO_EM_68.txt', 'ro_em_68.txt'),
 ('BA_EM_37.txt', 'ba_em_37.txt'),
 ('RO_EF_41.txt', 'ro_ef_41.txt'),
 ('MT_EF_92.txt', 'mt_ef_92.txt'),
 ('AP_EM_21.txt', 'ap_em_21.txt'),
 ('RN_EF_61.txt', 'rn_ef_61.txt'),
 ('ES_EF_Anos Iniciais_Linguagens_Intro_3.txt',
  'es_ef_anos_iniciais_linguagens_intro_3.txt'),
 ('MT_INF_3.txt', 'mt_inf_3.txt'),
 ('MA_EF_41.txt', 'ma_ef_41.txt'),
 ('PE_INF_8.txt', 'pe_inf_8.txt'),
 ('RS_EM_70.txt', 'rs_em_70.txt'),
 ('RS_INF e EF_12.txt', 'rs_inf_e_ef_12.txt'),
 ('PR_EM_48.txt', 'pr_em_48.txt'),
 ('GO_EM_28.txt', 'go_em_28.txt'),
 ('AL_EM_29.txt', 'al_em_29.txt'),
 ('MG_EF_Linguagens_LP_7.txt', 'mg_ef_linguagens_lp_7.txt'),
 ('PI_EM_30.txt', 'pi_em_30.txt'),
 ('SP_EM_10.txt', 'sp_em_10.txt'),
 ('TO_EM_40.txt', 'to_em_40.txt'),
 ('MT_EF_55.txt', 'mt_ef_55.txt'),
 ('RS_INF e EF_18.txt', 'rs_inf_e_ef_18.txt'),
 ('SP_EM_20.txt', 'sp_em_20.txt'),
 ('MG_EM_130.txt', 'mg_em_130.txt'),
 ('AC_EF_23.txt', 'ac_ef_23.txt'),
 ('PA_EM_4.txt', 'pa_em_4.txt'),
 ('RJ_EF_Intro_4.txt', 'rj_ef_intro_4.txt'),
 ('AL_EM_9.txt', 'al_em_9.txt'),
 ('PA_EF_3.txt', 'pa_ef_3.txt'),
 ('AL_INF_6.txt', 'al_inf_6.txt'),
 ('CE_INF e EF_26.txt', 'ce_inf_e_ef_26.txt'),
 ('BA_INF_3.txt', 'ba_inf_3.txt'),
 ('MG_EF_Linguagens_Ed Fis_7.txt', 'mg_ef_linguagens_ed_fis_7.txt'),
 ('PA_INF_16.txt', 'pa_inf_16.txt'),
 ('PR_EM_92.txt', 'pr_em_92.txt'),
 ('AM_INF_8.txt', 'am_inf_8.txt'),
 ('GO_EF_24.txt', 'go_ef_24.txt'),
 ('DF_EM_52.txt', 'df_em_52.txt'),
 ('TO_EM_4.txt', 'to_em_4.txt'),
 ('PB_INF_1.txt', 'pb_inf_1.txt'),
 ('CE_EM_47.txt', 'ce_em_47.txt'),
 ('BA_EF_31.txt', 'ba_ef_31.txt'),
 ('ES_EM_22.txt', 'es_em_22.txt'),
 ('PB_INF e EF_2.txt', 'pb_inf_e_ef_2.txt'),
 ('PA_EM_21.txt', 'pa_em_21.txt'),
 ('MT_EF_64.txt', 'mt_ef_64.txt'),
 ('RO_EM_74.txt', 'ro_em_74.txt'),
 ('TO_INF_15.txt', 'to_inf_15.txt'),
 ('AC_EF_32.txt', 'ac_ef_32.txt'),
 ('PB_EM_52.txt', 'pb_em_52.txt'),
 ('SC_EM_6.txt', 'sc_em_6.txt'),
 ('AL_EF_75.txt', 'al_ef_75.txt'),
 ('RS_EM_21.txt', 'rs_em_21.txt'),
 ('SE_EM_8.txt', 'se_em_8.txt'),
 ('TO_EF_28.txt', 'to_ef_28.txt'),
 ('TO_EM_51.txt', 'to_em_51.txt'),
 ('RN_INF_8.txt', 'rn_inf_8.txt'),
 ('PE_EM_23.txt', 'pe_em_23.txt'),
 ('PE_EF_40.txt', 'pe_ef_40.txt'),
 ('AM_EF_6.txt', 'am_ef_6.txt'),
 ('MA_INF e EF_14.txt', 'ma_inf_e_ef_14.txt'),
 ('PA_INF_3.txt', 'pa_inf_3.txt'),
 ('RO_EM_5.txt', 'ro_em_5.txt'),
 ('RR_EM_9.txt', 'rr_em_9.txt'),
 ('PI_EM_59.txt', 'pi_em_59.txt'),
 ('DF_INF_21.txt', 'df_inf_21.txt'),
 ('PI_EM_31.txt', 'pi_em_31.txt'),
 ('CE_EF_2.txt', 'ce_ef_2.txt'),
 ('PR_EM_3.txt', 'pr_em_3.txt'),
 ('MG_INF_Principios_4.txt', 'mg_inf_principios_4.txt'),
 ('PA_EM_46.txt', 'pa_em_46.txt'),
 ('AC_EM_47.txt', 'ac_em_47.txt'),
 ('MT_EM_17.txt', 'mt_em_17.txt'),
 ('PR_EM_37.txt', 'pr_em_37.txt'),
 ('PA_EM_33.txt', 'pa_em_33.txt'),
 ('PR_EM_108.txt', 'pr_em_108.txt'),
 ('TO_EF_29.txt', 'to_ef_29.txt'),
 ('CE_EF_34.txt', 'ce_ef_34.txt'),
 ('SC_INF e EF_17.txt', 'sc_inf_e_ef_17.txt'),
 ('PI_INF_4.txt', 'pi_inf_4.txt'),
 ('DF_EM_27.txt', 'df_em_27.txt'),
 ('RR_EM_18.txt', 'rr_em_18.txt'),
 ('CE_EM_11.txt', 'ce_em_11.txt'),
 ('RO_INF_46.txt', 'ro_inf_46.txt'),
 ('AL_EF_81.txt', 'al_ef_81.txt'),
 ('PA_EM_76.txt', 'pa_em_76.txt'),
 ('MT_INF_21.txt', 'mt_inf_21.txt'),
 ('PR_EM_93.txt', 'pr_em_93.txt'),
 ('RN_EM_3.txt', 'rn_em_3.txt'),
 ('RR_EM_39.txt', 'rr_em_39.txt'),
 ('AP_EF_38.txt', 'ap_ef_38.txt'),
 ('RO_EF_66.txt', 'ro_ef_66.txt'),
 ('PE_EF_7.txt', 'pe_ef_7.txt'),
 ('MA_INF e EF_10.txt', 'ma_inf_e_ef_10.txt'),
 ('MA_INF e EF_4.txt', 'ma_inf_e_ef_4.txt'),
 ('RN_EF_11.txt', 'rn_ef_11.txt'),
 ('MT_INF_4.txt', 'mt_inf_4.txt'),
 ('MG_EM_120.txt', 'mg_em_120.txt'),
 ('GO_INF e EF_7.txt', 'go_inf_e_ef_7.txt'),
 ('GO_EF_12.txt', 'go_ef_12.txt'),
 ('SC_INF e EF_11.txt', 'sc_inf_e_ef_11.txt'),
 ('PI_EF_37.txt', 'pi_ef_37.txt'),
 ('TO_EM_36.txt', 'to_em_36.txt'),
 ('PR_EM_131.txt', 'pr_em_131.txt'),
 ('MG_INF_Planejamento_1.txt', 'mg_inf_planejamento_1.txt'),
 ('MA_EF_52.txt', 'ma_ef_52.txt'),
 ('MT_EF_69.txt', 'mt_ef_69.txt'),
 ('CE_EF_36.txt', 'ce_ef_36.txt'),
 ('AL_EF_35.txt', 'al_ef_35.txt'),
 ('AM_EF_25.txt', 'am_ef_25.txt'),
 ('MT_EF_71.txt', 'mt_ef_71.txt'),
 ('RN_EF_58.txt', 'rn_ef_58.txt'),
 ('MG_EF_Linguagens_Ingles_10.txt', 'mg_ef_linguagens_ingles_10.txt'),
 ('MA_EF_17.txt', 'ma_ef_17.txt'),
 ('PI_EF_4.txt', 'pi_ef_4.txt'),
 ('ES_EF_Anos Iniciais_Linguagens_Intro_4.txt',
  'es_ef_anos_iniciais_linguagens_intro_4.txt'),
 ('PA_EF_28.txt', 'pa_ef_28.txt'),
 ('TO_EM_50.txt', 'to_em_50.txt'),
 ('PR_EF_10.txt', 'pr_ef_10.txt'),
 ('MT_24.txt', 'mt_24.txt'),
 ('PR_EM_44.txt', 'pr_em_44.txt'),
 ('PE_INF_12.txt', 'pe_inf_12.txt'),
 ('MA_EF_15.txt', 'ma_ef_15.txt'),
 ('PA_EM_77.txt', 'pa_em_77.txt'),
 ('RR_EF_15.txt', 'rr_ef_15.txt'),
 ('AL_EM_14.txt', 'al_em_14.txt'),
 ('AM_INF_15.txt', 'am_inf_15.txt'),
 ('SP_EF_Matematica_6.txt', 'sp_ef_matematica_6.txt'),
 ('RR_EF_19.txt', 'rr_ef_19.txt'),
 ('DF_EF_9.txt', 'df_ef_9.txt'),
 ('PB_EF_37.txt', 'pb_ef_37.txt'),
 ('RS_INF e EF_6.txt', 'rs_inf_e_ef_6.txt'),
 ('CE_EF_27.txt', 'ce_ef_27.txt'),
 ('MT_EM_75.txt', 'mt_em_75.txt'),
 ('GO_EM_52.txt', 'go_em_52.txt'),
 ('RS_INF e EF_19.txt', 'rs_inf_e_ef_19.txt'),
 ('GO_INF_17.txt', 'go_inf_17.txt'),
 ('PI_EF_8.txt', 'pi_ef_8.txt'),
 ('SP_EM_5.txt', 'sp_em_5.txt'),
 ('AL_EF_7.txt', 'al_ef_7.txt'),
 ('MG_EM_128.txt', 'mg_em_128.txt'),
 ('PR_EM_134.txt', 'pr_em_134.txt'),
 ('GO_EF_5.txt', 'go_ef_5.txt'),
 ('MS_EM_7.txt', 'ms_em_7.txt'),
 ('BA_EM_26.txt', 'ba_em_26.txt'),
 ('AP_EF_24.txt', 'ap_ef_24.txt'),
 ('PI_EM_27.txt', 'pi_em_27.txt'),
 ('MS_INF e EF_15.txt', 'ms_inf_e_ef_15.txt'),
 ('PI_EM_14.txt', 'pi_em_14.txt'),
 ('AP_EM_50.txt', 'ap_em_50.txt'),
 ('MT_INF_15.txt', 'mt_inf_15.txt'),
 ('SE_EF_19.txt', 'se_ef_19.txt'),
 ('MT_11.txt', 'mt_11.txt'),
 ('TO_INF_13.txt', 'to_inf_13.txt'),
 ('AP_INF e EF_6.txt', 'ap_inf_e_ef_6.txt'),
 ('GO_INF_24.txt', 'go_inf_24.txt'),
 ('PR_EM_121.txt', 'pr_em_121.txt'),
 ('PR_EM_60.txt', 'pr_em_60.txt'),
 ('PR_EM_103.txt', 'pr_em_103.txt'),
 ('PA_EF_11.txt', 'pa_ef_11.txt'),
 ('DF_EM_16.txt', 'df_em_16.txt'),
 ('RS_EM_50.txt', 'rs_em_50.txt'),
 ('MT_18.txt', 'mt_18.txt'),
 ('DF_EM_19.txt', 'df_em_19.txt'),
 ('PE_EM_36.txt', 'pe_em_36.txt'),
 ('DF_INF_3.txt', 'df_inf_3.txt'),
 ('PR_EM_80.txt', 'pr_em_80.txt'),
 ('PB_EF_53.txt', 'pb_ef_53.txt'),
 ('RR_EM_31.txt', 'rr_em_31.txt'),
 ('AL_EF_39.txt', 'al_ef_39.txt'),
 ('PA_EM_98.txt', 'pa_em_98.txt'),
 ('PA_EM_17.txt', 'pa_em_17.txt'),
 ('MA_EM_36.txt', 'ma_em_36.txt'),
 ('MT_EM_30.txt', 'mt_em_30.txt'),
 ('TO_EF_38.txt', 'to_ef_38.txt'),
 ('CE_INF_4.txt', 'ce_inf_4.txt'),
 ('BA_EM_35.txt', 'ba_em_35.txt'),
 ('GO_INF_20.txt', 'go_inf_20.txt'),
 ('RS_EF_8.txt', 'rs_ef_8.txt'),
 ('AL_EM_44.txt', 'al_em_44.txt'),
 ('RR_INF_21.txt', 'rr_inf_21.txt'),
 ('MG_EM_116.txt', 'mg_em_116.txt'),
 ('PI_EF_22.txt', 'pi_ef_22.txt'),
 ('PB_EM_13.txt', 'pb_em_13.txt'),
 ('PR_EF_5.txt', 'pr_ef_5.txt'),
 ('AL_INF_2.txt', 'al_inf_2.txt'),
 ('RN_INF_2.txt', 'rn_inf_2.txt'),
 ('PR_EM_68.txt', 'pr_em_68.txt'),
 ('RN_EF_54.txt', 'rn_ef_54.txt'),
 ('PA_INF e EF_5.txt', 'pa_inf_e_ef_5.txt'),
 ('AP_EM_1.txt', 'ap_em_1.txt'),
 ('RS_EM_40.txt', 'rs_em_40.txt'),
 ('PB_EF_14.txt', 'pb_ef_14.txt'),
 ('AP_EM_42.txt', 'ap_em_42.txt'),
 ('PE_EM_4.txt', 'pe_em_4.txt'),
 ('MS_EM_39.txt', 'ms_em_39.txt'),
 ('PR_EM_140.txt', 'pr_em_140.txt'),
 ('PB_INF_27.txt', 'pb_inf_27.txt'),
 ('MA_EF_21.txt', 'ma_ef_21.txt'),
 ('MA_EF_26.txt', 'ma_ef_26.txt'),
 ('AL_EF_60.txt', 'al_ef_60.txt'),
 ('RO_EM_27.txt', 'ro_em_27.txt'),
 ('CE_EM_20.txt', 'ce_em_20.txt'),
 ('RS_EM_7.txt', 'rs_em_7.txt'),
 ('PI_EM_43.txt', 'pi_em_43.txt'),
 ('MA_INF e EF_11.txt', 'ma_inf_e_ef_11.txt'),
 ('SC_EM_55.txt', 'sc_em_55.txt'),
 ('MT_9.txt', 'mt_9.txt'),
 ('RJ_INF_Intro_5.txt', 'rj_inf_intro_5.txt'),
 ('AM_EF_52.txt', 'am_ef_52.txt'),
 ('BA_EM_47.txt', 'ba_em_47.txt'),
 ('PR_EF_3.txt', 'pr_ef_3.txt'),
 ('PA_EM_15.txt', 'pa_em_15.txt'),
 ('PR_EM_31.txt', 'pr_em_31.txt'),
 ('AM_INF_25.txt', 'am_inf_25.txt'),
 ('TO_INF_4.txt', 'to_inf_4.txt'),
 ('MS_EM_17.txt', 'ms_em_17.txt'),
 ('RS_INF e EF_14.txt', 'rs_inf_e_ef_14.txt'),
 ('MA_EM_46.txt', 'ma_em_46.txt'),
 ('MT_EM_73.txt', 'mt_em_73.txt'),
 ('ES_INF_7.txt', 'es_inf_7.txt'),
 ('TO_EM_75.txt', 'to_em_75.txt'),
 ('TO_EM_3.txt', 'to_em_3.txt'),
 ('MG_EF_Linguagens_LP_8.txt', 'mg_ef_linguagens_lp_8.txt'),
 ('PE_EM_43.txt', 'pe_em_43.txt'),
 ('CE_INF_7.txt', 'ce_inf_7.txt'),
 ('PI_EM_2.txt', 'pi_em_2.txt'),
 ('BA_INF e EF_21.txt', 'ba_inf_e_ef_21.txt'),
 ('RO_EF_106.txt', 'ro_ef_106.txt'),
 ('SE_EM_15.txt', 'se_em_15.txt'),
 ('PA_EM_78.txt', 'pa_em_78.txt'),
 ('AP_EF_40.txt', 'ap_ef_40.txt'),
 ('AM_EF_45.txt', 'am_ef_45.txt'),
 ('AL_EM_2.txt', 'al_em_2.txt'),
 ('RN_EF_12.txt', 'rn_ef_12.txt'),
 ('ES_INF_Intro_7.txt', 'es_inf_intro_7.txt'),
 ('MG_EF_Linguagens_ingles_1.txt', 'mg_ef_linguagens_ingles_1.txt'),
 ('PE_EM_49.txt', 'pe_em_49.txt'),
 ('AC_INF_22.txt', 'ac_inf_22.txt'),
 ('RN_EF_51.txt', 'rn_ef_51.txt'),
 ('AL_EF_51.txt', 'al_ef_51.txt'),
 ('RN_INF_27.txt', 'rn_inf_27.txt'),
 ('AL_INF_7.txt', 'al_inf_7.txt'),
 ('PE_EF_64.txt', 'pe_ef_64.txt'),
 ('PE_EM_7.txt', 'pe_em_7.txt'),
 ('PR_EM_55.txt', 'pr_em_55.txt'),
 ('PB_EF_52.txt', 'pb_ef_52.txt'),
 ('PR_EM_141.txt', 'pr_em_141.txt'),
 ('RN_EF_60.txt', 'rn_ef_60.txt'),
 ('SP_EM_6.txt', 'sp_em_6.txt'),
 ('PB_EM_88.txt', 'pb_em_88.txt'),
 ('GO_INF_21.txt', 'go_inf_21.txt'),
 ('RN_EF_9.txt', 'rn_ef_9.txt'),
 ('AL_EM_7.txt', 'al_em_7.txt'),
 ('PR_EM_130.txt', 'pr_em_130.txt'),
 ('AP_EM_32.txt', 'ap_em_32.txt'),
 ('GO_EF_10.txt', 'go_ef_10.txt'),
 ('RO_EM_114.txt', 'ro_em_114.txt'),
 ('ES_EF_anos iniciais_Ciencias da natureza_2.txt',
  'es_ef_anos_iniciais_ciencias_da_natureza_2.txt'),
 ('AP_INF_16.txt', 'ap_inf_16.txt'),
 ('RS_EF_3.txt', 'rs_ef_3.txt'),
 ('AC_EM_37.txt', 'ac_em_37.txt'),
 ('PE_EF_77.txt', 'pe_ef_77.txt'),
 ('RN_INF_33.txt', 'rn_inf_33.txt'),
 ('AL_EF_80.txt', 'al_ef_80.txt'),
 ('MG_EF_Linguagens_Ingles_11.txt', 'mg_ef_linguagens_ingles_11.txt'),
 ('TO_EM_19.txt', 'to_em_19.txt'),
 ('RR_EM_52.txt', 'rr_em_52.txt'),
 ('MT_EF_23.txt', 'mt_ef_23.txt'),
 ('RS_EM_6.txt', 'rs_em_6.txt'),
 ('BA_EM_50.txt', 'ba_em_50.txt'),
 ('PE_EF_54.txt', 'pe_ef_54.txt'),
 ('RO_EM_64.txt', 'ro_em_64.txt'),
 ('RN_EF_39.txt', 'rn_ef_39.txt'),
 ('RO_EM_78.txt', 'ro_em_78.txt'),
 ('TO_EM_39.txt', 'to_em_39.txt'),
 ('AM_INF_10.txt', 'am_inf_10.txt'),
 ('RS_INF_10.txt', 'rs_inf_10.txt'),
 ('CE_EF_13.txt', 'ce_ef_13.txt'),
 ('DF_EM_56.txt', 'df_em_56.txt'),
 ('RJ_INF e EF_Intro_2.txt', 'rj_inf_e_ef_intro_2.txt'),
 ('BA_INF_5.txt', 'ba_inf_5.txt'),
 ('PI_EF_2.txt', 'pi_ef_2.txt'),
 ('RO_EM_104.txt', 'ro_em_104.txt'),
 ('RR_EM_37.txt', 'rr_em_37.txt'),
 ('TO_EF_7.txt', 'to_ef_7.txt'),
 ('BA_INF_1.txt', 'ba_inf_1.txt'),
 ('PI_EF_12.txt', 'pi_ef_12.txt'),
 ('PR_EM_64.txt', 'pr_em_64.txt'),
 ('PR_INF_EF_17.txt', 'pr_inf_ef_17.txt'),
 ('PE_EM_6.txt', 'pe_em_6.txt'),
 ('RS_EM_64.txt', 'rs_em_64.txt'),
 ('DF_EM_30.txt', 'df_em_30.txt'),
 ('ES_EF_Anos Iniciais_Linguagens_LP_2.txt',
  'es_ef_anos_iniciais_linguagens_lp_2.txt'),
 ('PR_EM_9.txt', 'pr_em_9.txt'),
 ('TO_EF_30.txt', 'to_ef_30.txt'),
 ('RS_EM_91.txt', 'rs_em_91.txt'),
 ('PB_EM_65.txt', 'pb_em_65.txt'),
 ('MG_EM_129.txt', 'mg_em_129.txt'),
 ('RR_EM_42.txt', 'rr_em_42.txt'),
 ('GO_EM_33.txt', 'go_em_33.txt'),
 ('AC_INF e EF_7.txt', 'ac_inf_e_ef_7.txt'),
 ('SE_EF_1.txt', 'se_ef_1.txt'),
 ('CE_EM_29.txt', 'ce_em_29.txt'),
 ('TO_EM_6.txt', 'to_em_6.txt'),
 ('MA_EM_6.txt', 'ma_em_6.txt'),
 ('PI_EM_44.txt', 'pi_em_44.txt'),
 ('CE_EM_57.txt', 'ce_em_57.txt'),
 ('RJ_INF_cam exp_8.txt', 'rj_inf_cam_exp_8.txt'),
 ('AL_EM_30.txt', 'al_em_30.txt'),
 ('PR_EM_33.txt', 'pr_em_33.txt'),
 ('BA_EF_24.txt', 'ba_ef_24.txt'),
 ('PE_EF_53.txt', 'pe_ef_53.txt'),
 ('TO_EM_14.txt', 'to_em_14.txt'),
 ('AL_EM_39.txt', 'al_em_39.txt'),
 ('CE_EM_33.txt', 'ce_em_33.txt'),
 ('AL_EF_18.txt', 'al_ef_18.txt'),
 ('AP_INF_13.txt', 'ap_inf_13.txt'),
 ('PR_INF_EF_15.txt', 'pr_inf_ef_15.txt'),
 ('RN_EF_16.txt', 'rn_ef_16.txt'),
 ('RR_INF_22.txt', 'rr_inf_22.txt'),
 ('RS_EM_28.txt', 'rs_em_28.txt'),
 ('AP_EM_44.txt', 'ap_em_44.txt'),
 ('RR_EM_45.txt', 'rr_em_45.txt'),
 ('RO_EF_53.txt', 'ro_ef_53.txt'),
 ('PB_EF_26.txt', 'pb_ef_26.txt'),
 ('CE_INF_10.txt', 'ce_inf_10.txt'),
 ('PR_EM_7.txt', 'pr_em_7.txt'),
 ('RJ_EM_5.txt', 'rj_em_5.txt'),
 ('SC_EM_59.txt', 'sc_em_59.txt'),
 ('CE_EM_43.txt', 'ce_em_43.txt'),
 ('MG_EM_1.txt', 'mg_em_1.txt'),
 ('RJ_INF_camp exp_1.txt', 'rj_inf_camp_exp_1.txt'),
 ('RO_INF_10.txt', 'ro_inf_10.txt'),
 ('PE_EF_12.txt', 'pe_ef_12.txt'),
 ('PB_INF e EF_4.txt', 'pb_inf_e_ef_4.txt'),
 ('AM_EF_38.txt', 'am_ef_38.txt'),
 ('RS_EM_4.txt', 'rs_em_4.txt'),
 ('GO_EF_28.txt', 'go_ef_28.txt'),
 ('MA_EM_57.txt', 'ma_em_57.txt'),
 ('BA_EF_17.txt', 'ba_ef_17.txt'),
 ('RS_EM_63.txt', 'rs_em_63.txt'),
 ('AC_EM_51.txt', 'ac_em_51.txt'),
 ('RR_EM_23.txt', 'rr_em_23.txt'),
 ('GO_EF_11.txt', 'go_ef_11.txt'),
 ('PE_EM_11.txt', 'pe_em_11.txt'),
 ('CE_EF_1.txt', 'ce_ef_1.txt'),
 ('MG_EM_10.txt', 'mg_em_10.txt'),
 ('PR_EM_52.txt', 'pr_em_52.txt'),
 ('GO_EM_54.txt', 'go_em_54.txt'),
 ('RN_EM_46.txt', 'rn_em_46.txt'),
 ('MA_EF_57.txt', 'ma_ef_57.txt'),
 ('SP_EM_11.txt', 'sp_em_11.txt'),
 ('CE_EF_26.txt', 'ce_ef_26.txt'),
 ('RO_EM_10.txt', 'ro_em_10.txt'),
 ('ES_EF_anos iniciais_Ciencias da natureza__1.txt',
  'es_ef_anos_iniciais_ciencias_da_natureza__1.txt'),
 ('PA_EM_24.txt', 'pa_em_24.txt'),
 ('ES_EM_7.txt', 'es_em_7.txt'),
 ('PB_EF_32.txt', 'pb_ef_32.txt'),
 ('MA_EM_13.txt', 'ma_em_13.txt'),
 ('MA_EM_8.txt', 'ma_em_8.txt'),
 ('SC_EM_54.txt', 'sc_em_54.txt'),
 ('PE_EF_72.txt', 'pe_ef_72.txt'),
 ('CE_EF_30.txt', 'ce_ef_30.txt'),
 ('AC_EM_15.txt', 'ac_em_15.txt'),
 ('MT_EM_37.txt', 'mt_em_37.txt'),
 ('MS_EM_31.txt', 'ms_em_31.txt'),
 ('MT_EM_65.txt', 'mt_em_65.txt'),
 ('AL_EF_56.txt', 'al_ef_56.txt'),
 ('RO_EM_88.txt', 'ro_em_88.txt'),
 ('MS_INF e EF_35.txt', 'ms_inf_e_ef_35.txt'),
 ('RO_EM_71.txt', 'ro_em_71.txt'),
 ('BA_INF e EF_18.txt', 'ba_inf_e_ef_18.txt'),
 ('MG_EM_18.txt', 'mg_em_18.txt'),
 ('PE_INF_29.txt', 'pe_inf_29.txt'),
 ('MG_EM_52.txt', 'mg_em_52.txt'),
 ('AM_EF_47.txt', 'am_ef_47.txt'),
 ('RR_EF_67.txt', 'rr_ef_67.txt'),
 ('PR_EM_113.txt', 'pr_em_113.txt'),
 ('MG_INF_Camp exp_4.txt', 'mg_inf_camp_exp_4.txt'),
 ('MA_EF_42.txt', 'ma_ef_42.txt'),
 ('AM_INF_44.txt', 'am_inf_44.txt'),
 ('SP_EM_9.txt', 'sp_em_9.txt'),
 ('TO_INF_18.txt', 'to_inf_18.txt'),
 ('PA_EF_10.txt', 'pa_ef_10.txt'),
 ('RO_EF_25.txt', 'ro_ef_25.txt'),
 ('PA_EM_89.txt', 'pa_em_89.txt'),
 ('MA_EM_16.txt', 'ma_em_16.txt'),
 ('BA_EM_64.txt', 'ba_em_64.txt'),
 ('RS_EM_27.txt', 'rs_em_27.txt'),
 ('AC_EF_37.txt', 'ac_ef_37.txt'),
 ('PA_INF_12.txt', 'pa_inf_12.txt'),
 ('SC_INF e EF_2.txt', 'sc_inf_e_ef_2.txt'),
 ('PA_INF_9.txt', 'pa_inf_9.txt'),
 ('PI_EF_31.txt', 'pi_ef_31.txt'),
 ('MG_EF_Linguagens_Ingles_13.txt', 'mg_ef_linguagens_ingles_13.txt'),
 ('PR_EM_26.txt', 'pr_em_26.txt'),
 ('MG_EM_50.txt', 'mg_em_50.txt'),
 ('BA_INF e EF_22.txt', 'ba_inf_e_ef_22.txt'),
 ('RO_EM_34.txt', 'ro_em_34.txt'),
 ('RR_EF_53.txt', 'rr_ef_53.txt'),
 ('GO_EM_35.txt', 'go_em_35.txt'),
 ('GO_EF_46.txt', 'go_ef_46.txt'),
 ('SC_EM_49.txt', 'sc_em_49.txt'),
 ('PB_EM_63.txt', 'pb_em_63.txt'),
 ('PR_EM_116.txt', 'pr_em_116.txt'),
 ('MA_EM_48.txt', 'ma_em_48.txt'),
 ('RR_INF_6.txt', 'rr_inf_6.txt'),
 ('PB_EF_25.txt', 'pb_ef_25.txt'),
 ('PA_EM_39.txt', 'pa_em_39.txt'),
 ('MG_EM_132.txt', 'mg_em_132.txt'),
 ('ES_INF_Intro_8.txt', 'es_inf_intro_8.txt'),
 ('SC_EM_71.txt', 'sc_em_71.txt'),
 ('RJ_EF_Intro_1.txt', 'rj_ef_intro_1.txt'),
 ('BA_EM_28.txt', 'ba_em_28.txt'),
 ('RS_EM_78.txt', 'rs_em_78.txt'),
 ('RS_INF e EF_1.txt', 'rs_inf_e_ef_1.txt'),
 ('MA_EF_33.txt', 'ma_ef_33.txt'),
 ('RO_EM_69.txt', 'ro_em_69.txt'),
 ('BA_EF_29.txt', 'ba_ef_29.txt'),
 ('MT_EF_44.txt', 'mt_ef_44.txt'),
 ('RN_INF_35.txt', 'rn_inf_35.txt'),
 ('MG_EM_94.txt', 'mg_em_94.txt'),
 ('AC_EF_12.txt', 'ac_ef_12.txt'),
 ('DF_INF_16.txt', 'df_inf_16.txt'),
 ('MG_EM_25.txt', 'mg_em_25.txt'),
 ('PA_EM_41.txt', 'pa_em_41.txt'),
 ('AM_EF_7.txt', 'am_ef_7.txt'),
 ('PE_EM_8.txt', 'pe_em_8.txt'),

## Count source files by Brazilian state code

In [5]:
from collections import Counter
from pathlib import Path
import pandas as pd

source_dir = Path("corpus/00_source")

state_counts = Counter(
    path.name.split("_", 1)[0]
    for path in source_dir.iterdir()
    if path.is_file()
)

state_counts_df = (
    pd.Series(state_counts, name="file_count")
    .rename_axis("state_code")
    .sort_index()
    .reset_index()
)

state_counts_df

   state_code  file_count
0          ac         139
1          al         170
2          am         148
3          ap         134
4          ba         135
5          ce         148
6          df         103
7          es         105
8          go         150
9          ma         146
10         mg         293
11         ms         102
12         mt         227
13         pa         175
14         pb         209
15         pe         158
16         pi         127
17         pr         178
18         rj          98
19         rn         149
20         ro         279
21         rr         164
22         rs         141
23         sc         118
24         se          68
25         sp         103
26         to         145

## Inspect educational stage and discipline labels from filenames

In [6]:
from pathlib import Path

source_dir = Path("corpus/00_source")

stage_discipline_labels = {
    filename.stem[filename.stem.find("_") + 1:filename.stem.rfind("_")]
    for filename in source_dir.glob("*.txt")
    if filename.stem.count("_") >= 2
}

stage_discipline_labels = set(sorted(stage_discipline_labels))

stage_discipline_labels

{'ef',
 'ef_anos_finais_ciencias_da',
 'ef_anos_finais_linguagens_ingles',
 'ef_anos_iniciais_arte',
 'ef_anos_iniciais_ciencias_da_natureza',
 'ef_anos_iniciais_ciencias_da_natureza_',
 'ef_anos_iniciais_ciencias_humanas',
 'ef_anos_iniciais_ciencias_humanas_geo',
 'ef_anos_iniciais_ciencias_humanas_historia',
 'ef_anos_iniciais_ensino_religioso',
 'ef_anos_iniciais_linguagens_arte',
 'ef_anos_iniciais_linguagens_ed_fis',
 'ef_anos_iniciais_linguagens_intro',
 'ef_anos_iniciais_linguagens_lp',
 'ef_anos_iniciais_matematica',
 'ef_ch_geo',
 'ef_ch_his',
 'ef_ciencias',
 'ef_ciencias_da_natureza',
 'ef_ciencias_humanas',
 'ef_ciencias_humanas_geo',
 'ef_ciencias_humanas_his',
 'ef_ciencias_humanas_intro',
 'ef_ciencias_humas_intro',
 'ef_e_em_tema',
 'ef_ensino_religioso',
 'ef_er',
 'ef_intro',
 'ef_linguagens',
 'ef_linguagens_arte',
 'ef_linguagens_ed_fis',
 'ef_linguagens_ingles',
 'ef_linguagens_lp',
 'ef_matematica',
 'em',
 'inf',
 'inf_1',
 'inf_10_camp',
 'inf_12_camp_exp_escuta_',
 'inf_2',
 'inf_3',
 'inf_4',
 'inf_5',
 'inf_8_camp',
 'inf_adaptacoes',
 'inf_alfabetizar',
 'inf_aspectos',
 'inf_cam_exp',
 'inf_camp_ex',
 'inf_camp_exp',
 'inf_campo_e',
 'inf_campo_exp',
 'inf_concepcao_de',
 'inf_curriculo',
 'inf_curriculo_e',
 'inf_direitos_de',
 'inf_diversidade_etnico',
 'inf_e_ef',
 'inf_e_ef_apresentacao',
 'inf_e_ef_intro',
 'inf_ef',
 'inf_formacao',
 'inf_formacao_de',
 'inf_funcao',
 'inf_inclusao',
 'inf_intro',
 'inf_intro_14_matriz',
 'inf_intro_16_temas',
 'inf_intro_19',
 'inf_intro_20',
 'inf_natureza',
 'inf_organizacao',
 'inf_papel_do',
 'inf_planejamento',
 'inf_principios',
 'inf_respeito_e',
 'inf_transicoes'}

## Normalise double underscores in source filenames

In [7]:
from pathlib import Path

source_dir = Path("corpus/00_source")

renamed_files = []

for path in source_dir.glob("*.txt"):
    new_name = path.name
    while "__" in new_name:
        new_name = new_name.replace("__", "_")

    if new_name != path.name:
        new_path = path.with_name(new_name)

        if new_path.exists():
            raise FileExistsError(f"Cannot rename {path.name} to {new_name}: target already exists.")

        path.rename(new_path)
        renamed_files.append((path.name, new_name))

renamed_files

[('es_inf_12_camp_exp_escuta__fala.txt', 'es_inf_12_camp_exp_escuta_fala.txt'),
 ('es_ef_anos_iniciais_ciencias_da_natureza__1.txt',
  'es_ef_anos_iniciais_ciencias_da_natureza_1.txt')]

## Organise source files by Brazilian state code

In [8]:
from collections import Counter
from pathlib import Path
import shutil

source_dir = Path("corpus/00_source")
per_state_dir = Path("corpus/00_source_per_state")

per_state_dir.mkdir(parents=True, exist_ok=True)

copied_files = []

for path in sorted(source_dir.iterdir()):
    if not path.is_file():
        continue

    state_code = path.name.split("_", 1)[0].lower()
    state_dir = per_state_dir / state_code
    state_dir.mkdir(parents=True, exist_ok=True)

    target_path = state_dir / path.name
    shutil.copy2(path, target_path)
    copied_files.append((path.name, state_code, str(target_path)))

per_state_counts_df = (
    pd.Series(Counter(state for _, state, _ in copied_files), name="file_count")
    .rename_axis("state_code")
    .sort_index()
    .reset_index()
)

per_state_counts_df

   state_code  file_count
0          ac         139
1          al         170
2          am         148
3          ap         134
4          ba         135
5          ce         148
6          df         103
7          es         105
8          go         150
9          ma         146
10         mg         293
11         ms         102
12         mt         227
13         pa         175
14         pb         209
15         pe         158
16         pi         127
17         pr         178
18         rj          98
19         rn         149
20         ro         279
21         rr         164
22         rs         141
23         sc         118
24         se          68
25         sp         103
26         to         145

## Create source-file inventory by Brazilian state

In [9]:
from pathlib import Path
import pandas as pd

source_per_state_dir = Path("corpus/00_source_per_state")

records = []

for state_dir in sorted(source_per_state_dir.iterdir()):
    if not state_dir.is_dir():
        continue

    state = state_dir.name

    for path in sorted(state_dir.iterdir()):
        if path.is_file():
            records.append(
                {
                    "filename": path.name,
                    "state": state,
                    "filepath": path.as_posix(),
                }
            )

df_brazilian_educational_guidelines = pd.DataFrame(
    records,
    columns=["filename", "state", "filepath"],
)

df_brazilian_educational_guidelines

          filename state                                    filepath
0      ac_ef_1.txt    ac   corpus/00_source_per_state/ac/ac_ef_1.txt
1     ac_ef_10.txt    ac  corpus/00_source_per_state/ac/ac_ef_10.txt
2     ac_ef_11.txt    ac  corpus/00_source_per_state/ac/ac_ef_11.txt
3     ac_ef_12.txt    ac  corpus/00_source_per_state/ac/ac_ef_12.txt
4     ac_ef_13.txt    ac  corpus/00_source_per_state/ac/ac_ef_13.txt
...            ...   ...                                         ...
4107  to_inf_5.txt    to  corpus/00_source_per_state/to/to_inf_5.txt
4108  to_inf_6.txt    to  corpus/00_source_per_state/to/to_inf_6.txt
4109  to_inf_7.txt    to  corpus/00_source_per_state/to/to_inf_7.txt
4110  to_inf_8.txt    to  corpus/00_source_per_state/to/to_inf_8.txt
4111  to_inf_9.txt    to  corpus/00_source_per_state/to/to_inf_9.txt

[4112 rows x 3 columns]

## Add original text word counts

In [3]:
from pathlib import Path
import re

def count_words_in_file(filepath):
    text = Path(filepath).read_text(encoding="utf-8")
    return len(re.findall(r"\b\w+\b", text, flags=re.UNICODE))

df_brazilian_educational_guidelines["word_count_original"] = (
    df_brazilian_educational_guidelines["filepath"].apply(count_words_in_file)
)

df_brazilian_educational_guidelines

,filename,state,filepath,word_count_original
0,ac_ef_1.txt,ac,corpus/00_source_per_state/ac/ac_ef_1.txt,2075
1,ac_ef_10.txt,ac,corpus/00_source_per_state/ac/ac_ef_10.txt,1084
2,ac_ef_11.txt,ac,corpus/00_source_per_state/ac/ac_ef_11.txt,832
3,ac_ef_12.txt,ac,corpus/00_source_per_state/ac/ac_ef_12.txt,369
4,ac_ef_13.txt,ac,corpus/00_source_per_state/ac/ac_ef_13.txt,332
...,...,...,...,...
4107,to_inf_5.txt,to,corpus/00_source_per_state/to/to_inf_5.txt,2260
4108,to_inf_6.txt,to,corpus/00_source_per_state/to/to_inf_6.txt,517
4109,to_inf_7.txt,to,corpus/00_source_per_state/to/to_inf_7.txt,291
4110,to_inf_8.txt,to,corpus/00_source_per_state/to/to_inf_8.txt,613
4111,to_inf_9.txt,to,corpus/00_source_per_state/to/to_inf_9.txt,949

## Identify the longest and shortest original texts

In [4]:
df_brazilian_educational_guidelines["word_count_original"].describe()

count    4112.000000
mean      991.754377
std       747.611712
min        98.000000
25%       510.750000
50%       788.500000
75%      1251.000000
max      7599.000000
Name: word_count_original, dtype: float64

## Load Brazilian educational guidelines data

In [1]:
# Load Brazilian educational guidelines data

import pandas as pd

df_brazilian_educational_guidelines = pd.read_json(
    "corpus/brazilian_educational_guidelines.ndjson",
    lines=True,
)

df_brazilian_educational_guidelines.head()

,filename,state,filepath,word_count_original
0,ac_ef_1.txt,ac,corpus/00_source_per_state/ac/ac_ef_1.txt,2075
1,ac_ef_10.txt,ac,corpus/00_source_per_state/ac/ac_ef_10.txt,1084
2,ac_ef_11.txt,ac,corpus/00_source_per_state/ac/ac_ef_11.txt,832
3,ac_ef_12.txt,ac,corpus/00_source_per_state/ac/ac_ef_12.txt,369
4,ac_ef_13.txt,ac,corpus/00_source_per_state/ac/ac_ef_13.txt,332

## Add denoised file paths

In [5]:
# Add denoised file paths

from pathlib import Path

source_dir = Path("corpus/00_source_per_state")
denoised_dir = Path("corpus/02_extracted")

filepath_col_index = df_brazilian_educational_guidelines.columns.get_loc("filepath")

filepath_denoised = df_brazilian_educational_guidelines["filepath"].apply(
    lambda filepath: str(
        denoised_dir
        / Path(filepath).relative_to(source_dir).with_suffix(".md")
    )
)

if "filepath_denoised" in df_brazilian_educational_guidelines.columns:
    df_brazilian_educational_guidelines = df_brazilian_educational_guidelines.drop(
        columns="filepath_denoised"
    )

df_brazilian_educational_guidelines.insert(
    filepath_col_index + 1,
    "filepath_denoised",
    filepath_denoised,
)

df_brazilian_educational_guidelines.head()

,filename,state,filepath,filepath_denoised,word_count_original
0,ac_ef_1.txt,ac,corpus/00_source_per_state/ac/ac_ef_1.txt,corpus/02_extracted/ac/ac_ef_1.md,2075
1,ac_ef_10.txt,ac,corpus/00_source_per_state/ac/ac_ef_10.txt,corpus/02_extracted/ac/ac_ef_10.md,1084
2,ac_ef_11.txt,ac,corpus/00_source_per_state/ac/ac_ef_11.txt,corpus/02_extracted/ac/ac_ef_11.md,832
3,ac_ef_12.txt,ac,corpus/00_source_per_state/ac/ac_ef_12.txt,corpus/02_extracted/ac/ac_ef_12.md,369
4,ac_ef_13.txt,ac,corpus/00_source_per_state/ac/ac_ef_13.txt,corpus/02_extracted/ac/ac_ef_13.md,332

## Add denoised word counts

In [6]:
# Add denoised word counts

from pathlib import Path

word_count_original_col_index = df_brazilian_educational_guidelines.columns.get_loc(
    "word_count_original"
)

word_count_denoised = df_brazilian_educational_guidelines["filepath_denoised"].apply(
    lambda filepath: len(Path(filepath).read_text(encoding="utf-8").split())
)

if "word_count_denoised" in df_brazilian_educational_guidelines.columns:
    df_brazilian_educational_guidelines = df_brazilian_educational_guidelines.drop(
        columns="word_count_denoised"
    )

df_brazilian_educational_guidelines.insert(
    word_count_original_col_index + 1,
    "word_count_denoised",
    word_count_denoised,
)

df_brazilian_educational_guidelines.head()

,filename,state,filepath,filepath_denoised,word_count_original,word_count_denoised
0,ac_ef_1.txt,ac,corpus/00_source_per_state/ac/ac_ef_1.txt,corpus/02_extracted/ac/ac_ef_1.md,2075,2064
1,ac_ef_10.txt,ac,corpus/00_source_per_state/ac/ac_ef_10.txt,corpus/02_extracted/ac/ac_ef_10.md,1084,1073
2,ac_ef_11.txt,ac,corpus/00_source_per_state/ac/ac_ef_11.txt,corpus/02_extracted/ac/ac_ef_11.md,832,879
3,ac_ef_12.txt,ac,corpus/00_source_per_state/ac/ac_ef_12.txt,corpus/02_extracted/ac/ac_ef_12.md,369,367
4,ac_ef_13.txt,ac,corpus/00_source_per_state/ac/ac_ef_13.txt,corpus/02_extracted/ac/ac_ef_13.md,332,341

## Identify the longest and shortest denoised texts

In [7]:
df_brazilian_educational_guidelines["word_count_denoised"].describe()

count    4112.000000
mean      975.624027
std       733.211163
min        22.000000
25%       501.750000
50%       775.000000
75%      1221.250000
max      6516.000000
Name: word_count_denoised, dtype: float64

## Export Brazilian educational guidelines inventory

In [8]:
from pathlib import Path

corpus_dir = Path("corpus")
corpus_dir.mkdir(parents=True, exist_ok=True)

output_stem = corpus_dir / "brazilian_educational_guidelines"

df_brazilian_educational_guidelines.to_json(
    output_stem.with_suffix(".ndjson"),
    orient="records",
    lines=True,
    force_ascii=False,
)

df_brazilian_educational_guidelines.to_csv(
    output_stem.with_suffix(".tsv"),
    sep="\t",
    index=False,
    encoding="utf-8",
)

df_brazilian_educational_guidelines.to_excel(
    output_stem.with_suffix(".xlsx"),
    index=False,
)

[
    output_stem.with_suffix(".ndjson").as_posix(),
    output_stem.with_suffix(".tsv").as_posix(),
    output_stem.with_suffix(".xlsx").as_posix(),
]

['corpus/brazilian_educational_guidelines.ndjson',
 'corpus/brazilian_educational_guidelines.tsv',
 'corpus/brazilian_educational_guidelines.xlsx']

## Load SAS factor scores

In [1]:
import pandas as pd

df_cl_st1_ph2_anna_scores_only = pd.read_csv(
    "sas/output_cl_st1_ph2_anna/cl_st1_ph2_anna_scores_only.tsv",
    sep="\t",
)

Drop `vnnnnnn` columns

In [3]:
df_cl_st1_ph2_anna_scores_only = df_cl_st1_ph2_anna_scores_only.drop(
    columns=df_cl_st1_ph2_anna_scores_only.filter(regex=r"^v\d{6}$").columns
)

In [4]:
df_cl_st1_ph2_anna_scores_only

     filename state group  fac1  fac2  fac3  fac4  fac5  fac6
0     t000001    ac    ac    37    13     2    -1     1     2
1     t000002    ac    ac    10     2     0    10     3     1
2     t000003    ac    ac    24    12    -1     0     4     4
3     t000004    ac    ac    14     3     2     3     3     0
4     t000005    ac    ac    43     8     5     0     1     2
...       ...   ...   ...   ...   ...   ...   ...   ...   ...
4107  t004108    to    to    19     6    16     1     0     2
4108  t004109    to    to     5     0    18     1     1     0
4109  t004110    to    to    15     1    21     2     1     1
4110  t004111    to    to     4     1    15     0     1     0
4111  t004112    to    to    12     0    16     1     1     4

[4112 rows x 9 columns]

## Export SAS factor scores

In [5]:
from pathlib import Path

corpus_dir = Path("sas")
corpus_dir.mkdir(parents=True, exist_ok=True)

output_stem = corpus_dir / "cl_st1_ph2_anna_scores_only"

df_cl_st1_ph2_anna_scores_only.to_json(
    output_stem.with_suffix(".ndjson"),
    orient="records",
    lines=True,
    force_ascii=False,
)

df_cl_st1_ph2_anna_scores_only.to_csv(
    output_stem.with_suffix(".tsv"),
    sep="\t",
    index=False,
    encoding="utf-8",
)

df_cl_st1_ph2_anna_scores_only.to_excel(
    output_stem.with_suffix(".xlsx"),
    index=False,
)

[
    output_stem.with_suffix(".ndjson").as_posix(),
    output_stem.with_suffix(".tsv").as_posix(),
    output_stem.with_suffix(".xlsx").as_posix(),
]

['sas/cl_st1_ph2_anna_scores_only.ndjson',
 'sas/cl_st1_ph2_anna_scores_only.tsv',
 'sas/cl_st1_ph2_anna_scores_only.xlsx']

## Collect POS tags for lemma `que`

In [3]:
from pathlib import Path

base = Path("corpus/07_tagged")
que_tags = set()

for tagged_file in base.rglob("*.txt"):
    with tagged_file.open("r", encoding="utf-8") as f:
        for line in f:
            parts = line.strip().split("\t")
            if len(parts) >= 3 and parts[2].strip().lower() == "que":
                que_tags.add(parts[1])

que_tags

{'ADP',
 'ADV',
 'DET.Int',
 'DET.Int.Fem.Plur',
 'DET.Int.Fem.Sing',
 'DET.Int.Masc.Plur',
 'DET.Int.Masc.Sing',
 'DET.Masc.Plur',
 'DET.Masc.Sing',
 'NOUN.Masc.Sing',
 'PRON.Int.Fem.Plur',
 'PRON.Int.Masc.Sing',
 'PRON.Masc.Sing',
 'PRON.Rel',
 'PRON.Rel.Fem',
 'PRON.Rel.Fem.Plur',
 'PRON.Rel.Fem.Sing',
 'PRON.Rel.Masc.Plur',
 'PRON.Rel.Masc.Sing',
 'PROPN',
 'PROPN.Masc.Sing',
 'PROPN.Sing',
 'SCONJ'}